name: Build and Publish Doggo

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI
    inputs:
      version:
        description: 'Version or tag for this build'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish app
        run: |
          dotnet publish ./src/Doggo.Cli/Doggo.Cli.csproj -c Release -r win-x64 --self-contained true `
            -p:PublishSingleFile=true `
            -p:UseAppHost=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -o ./publish

      - name: Rename output to doggo.exe
        run: Rename-Item ./publish/Doggo.Cli.exe doggo.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: doggo
          path: ./publish/doggo.exe

      - name: Create GitHub Release Tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git tag ${{ github.event.inputs.version }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/doggo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
